GPU Memory Usage:
Now CUDA_VISIBLE_DEVICES is set to:
CUDA_VISIBLE_DEVICES=0,1
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.
  warnings.warn("`config` is deprecated and will be removed soon.")
[10/31/23 03:02:38] INFO     colossalai - colossalai - INFO:                    
                             /mnt/miniconda3/envs/coati/lib/python3.10/site-pack
                             ages/colossalai/initialize.py:63 launch            
                    INFO     colossalai - colossalai - INFO: Distributed        
                             environment is initialized, world size: 2          
/mnt/ColossalAI/applications/Chat/examples/train_prompts.py:34: UserWarning: LoRA weights should be merged with the model weights
  warnings.warn("LoRA weights should be merged with the model weights")
[10/31/23 03:02:38] INFO     colossalai - colossalai - INFO:                    
                             /mnt/miniconda3/envs/coati/lib/python3.10/site-pack
                             ages/colossalai/initialize.py:63 launch            
                    INFO     colossalai - colossalai - INFO: Distributed        
                             environment is initialized, world size: 2          
/mnt/ColossalAI/applications/Chat/examples/train_prompts.py:34: UserWarning: LoRA weights should be merged with the model weights
  warnings.warn("LoRA weights should be merged with the model weights")
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:00<00:01,  1.28it/s]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:01<00:00,  1.29it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.54it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.46it/s]
Some weights of the model checkpoint at /mnt/hf/polyglot-ko-1.3b were not used when initializing GPTNeoXModel: ['embed_out.weight']
- This IS expected if you are initializing GPTNeoXModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPTNeoXModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:00<00:01,  1.47it/s]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:01<00:00,  1.49it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  1.77it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  1.68it/s]
Some weights of the model checkpoint at /mnt/hf/polyglot-ko-1.3b were not used when initializing GPTNeoXModel: ['embed_out.weight']
- This IS expected if you are initializing GPTNeoXModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPTNeoXModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:00<00:01,  1.51it/s]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:01<00:00,  1.50it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  1.75it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  1.67it/s]
Some weights of the model checkpoint at /mnt/hf/polyglot-ko-1.3b were not used when initializing GPTNeoXModel: ['embed_out.weight']
- This IS expected if you are initializing GPTNeoXModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPTNeoXModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading checkpoint shards:  33%|███▎      | 1/3 [00:00<00:01,  1.83it/s]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:01<00:00,  1.84it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  2.17it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:01<00:00,  2.07it/s]
Some weights of the model checkpoint at /mnt/hf/polyglot-ko-1.3b were not used when initializing GPTNeoXModel: ['embed_out.weight']
- This IS expected if you are initializing GPTNeoXModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPTNeoXModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/mnt/ColossalAI/applications/Chat/examples/train_prompts.py", line 270, in <module>
    main(args)
  File "/mnt/ColossalAI/applications/Chat/examples/train_prompts.py", line 106, in main
    actor.to(torch.bfloat16).to(torch.cuda.current_device())
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 1; 39.45 GiB total capacity; 38.36 GiB already allocated; 32.25 MiB free; 38.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/mnt/ColossalAI/applications/Chat/examples/train_prompts.py", line 270, in <module>
    main(args)
  File "/mnt/ColossalAI/applications/Chat/examples/train_prompts.py", line 106, in main
    actor.to(torch.bfloat16).to(torch.cuda.current_device())
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 39.45 GiB total capacity; 38.36 GiB already allocated; 32.25 MiB free; 38.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23714) of binary: /mnt/miniconda3/envs/coati/bin/python
Traceback (most recent call last):
  File "/mnt/miniconda3/envs/coati/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/miniconda3/envs/coati/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_prompts.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-31_03:14:06
  host      : gpu-server-03
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 23715)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-31_03:14:06
  host      : gpu-server-03
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 23714)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
